### ISSUE TITLE
Confusing Japan Event

### ISSUE THREAD

**Issue by donbg** [jespertjee/FR#67]
I got this event:
![image](https://user-images.githubusercontent.com/40672374/51281432-4acca000-19da-11e9-9800-5090285e1219.png)

I have no idea what this event is talking about and it uses very confusing language. "The Americans have notified us on the Standard Oil monopoly in Texas".. What is that supposed to mean? And why does some monopoly in Texas have anything to do with Japan? "In order to help counter the trust that John D. Rockefeller has..." why do I want to counter that, what does that have to do with Japan? Who even is this guy? (I know who Rockefeller is, but isn't he irrelevant to Japan?) Also saying "counter" and then "combat" in the same sentence is redundant.

**Comment by Drowse** [comment]
redid the loc to better explain things

"The Americans have notified us on Standard Oil, one of the largest Oil Companies on Earth, and their monopoly over the Texan Oil industry. In order to help counter the trust that John D. Rockafeller has, the American negotiator has asked us to promote investments by the Zaibatsus, such as Nippon Oil, into the American market. This deal would help Japan secure a stable source of US oil for our growing needs while the Americans would gain a much needed source of foreign capital.."
